---
cost: 2.1819
title: industry-news
updated_at: 2026-02-02T00:00:00Z
---

| ID | Date | Company | News Title | Link | Summary |
|---|---|---|---|---|
| 20260130-ai-agent-protocols | 2026-01-30 | Multiple | Deciphering the Alphabet Soup of Agentic AI Protocols | https://www.theregister.com/2026/01/30/agnetic_ai_protocols_mcp_utcp_a2a_etc/ | Industry struggles with competing AI agent protocols including MCP, A2A, UTCP, ANP, and NLIP. MCP has emerged as de facto standard for agent-to-tool communication despite security flaws, while A2A leads agent-to-agent protocols after merging with IBM's ACP under Linux Foundation. |
| 20260130-ai-infrastructure-gdp | 2026-01-30 | Gartner | Countries Must Invest 1% of GDP in AI Infrastructure for Digital Sovereignty | https://www.theregister.com/2026/01/30/1pc_gdp_ai_gartner/ | Gartner predicts countries seeking digital sovereignty will need to invest at least 1% of GDP into AI infrastructure by 2029. 35% of countries will be locked into region-specific AI platforms by 2027, driving up costs through reduced collaboration and duplication of effort. |
| 20260129-ai-agent-identity-crisis | 2026-01-29 | Multiple | AI Agents Running Wild: Companies Give Untrustworthy Bots Keys to the Kingdom | https://www.theregister.com/2026/01/29/ai_agent_identity_security/ | Security experts warn that corporate AI agents are "absolutely ungoverned" with companies treating them like "thousands of interns running around in production environments." Organizations struggle to manage agentic identities as 40% of enterprise apps will integrate AI agents by 2026. |
| 20260129-meta-ai-infrastructure | 2026-01-29 | Meta | Meta to Pour $135B into AI Infrastructure in 2026 | https://www.theregister.com/2026/01/29/meta_2026_infrastructure_spend/ | Meta announces massive $135 billion infrastructure investment for 2026, betting big on "personal superintelligence" as Zuckerberg pushes to dominate the AI race with unprecedented spending on compute and data centers. |
| 20260129-dow-chemical-ai-layoffs | 2026-01-29 | Dow Chemical | Dow Chemical Says AI is Behind 4,500 Job Cuts | https://www.theregister.com/2026/01/29/dow_chemical_ai_layoffs/ | The 129-year-old chemical company announces 4,500 layoffs driven by AI implementation using Palantir-rival C3's AI platform, marking one of the largest AI-driven workforce reductions in the industrial sector. |
| 20260129-agent-trace-standard | 2026-01-29 | Multiple | Agent Trace Open Standard Launched for AI Code Attribution | https://agent-trace.dev/ | Major AI coding companies including Cursor, Cognition, Cloudflare, Vercel, git-ai, and OpenCode announce Agent Trace, an open vendor-neutral specification for tracking AI-generated code contributions alongside human authorship in version-controlled codebases. |
| 20260129-anthropic-ai-100-percent | 2026-01-29 | Anthropic/OpenAI | Top Engineers Say AI Now Writes 100% of Their Code | https://fortune.com/2026/01/29/100-percent-of-code-at-anthropic-and-openai-is-now-ai-written-boris-cherny-roon/ | Engineers at Anthropic and OpenAI report that AI now writes 100% of their code, marking a major milestone in AI-assisted development. This represents a dramatic shift from traditional coding practices to AI-native development workflows. |
| 20260129-opsera-ai-coding-report | 2026-01-29 | Opsera | AI Coding Impact Report Shows 29% of US Code is AI-Generated | https://www.prnewswire.com/news-releases/new-opsera-report-reveals-how-ai-is-transforming-software-delivery-and-driving-business-outcomes-302673996.html | Opsera's 2026 AI Coding Impact Benchmark Report analyzing data from 250,000+ developers reveals AI-assisted development has reached mainstream adoption, with 29% of new US software code now AI-generated. |
| 20260128-claude-code-security-flaw | 2026-01-28 | Anthropic | Claude Code Can't Keep Secrets: AI Reads Protected Files Despite .claudeignore | https://www.theregister.com/2026/01/28/claude_code_ai_secrets_files/ | Critical security flaw discovered in Claude Code where the AI assistant ignores .claudeignore and .gitignore files, potentially exposing passwords, API keys, and other secrets. Multiple bug reports since November 2025 remain unaddressed despite being marked "HIGH PRIORITY." |
| 20260128-anthropic-ceo-regulation | 2026-01-28 | Anthropic | Anthropic CEO Writes 20,000+ Word Essay Against AI Regulation | https://www.theregister.com/2026/01/28/anthropic_ceo_regulation_essay/ | Dario Amodei publishes massive essay arguing against AI regulation in what critics call a "thinly veiled plea" to avoid oversight, sparking debate about self-regulation versus government intervention in the AI industry. |
| 20260128-cognition-london-office | 2026-01-28 | Cognition | Cognition Opens London Office to Expand Devin AI in Europe | https://www.cognition.ai/blog/cognition-london | Cognition expands to Europe with new London office, marking significant international expansion for the Devin AI software engineer platform as demand grows for autonomous coding solutions. |
| 20260128-cognizant-cognition | 2026-01-28 | Cognition | Cognizant Partners with Cognition to Scale Devin AI | https://www.prnewswire.com/news-releases/cognizant-and-cognition-partner-to-scale-autonomous-software-engineering-and-deliver-business-value-across-enterprise-operations-302671608.html | Cognizant announced strategic partnership with Cognition to bring Devin AI autonomous software engineer to enterprises. Unlike traditional coding assistants, Devin can take on end-to-end development tasks independently, planning, executing and validating work across complex systems. |
| 20260128-sk-hynix-ai-co | 2026-01-28 | SK Hynix | SK Hynix Launches $10B "AI Co." for Datacenter Solutions | https://www.theregister.com/2026/01/28/sk_hynix_ai_co/ | SK Hynix is creating a new subsidiary called "AI Co." with $10 billion investment to provide integrated AI datacenter solutions combining hardware, software, and services. The company will restructure its Solidigm SSD subsidiary as part of the launch in February. |
| 20260128-ai-agents-production | 2026-01-28 | Redis | AI Agent Hype Cools as Enterprises Struggle with Production | https://www.theregister.com/2026/01/28/ai_agents_redis/ | Redis CEO Rowan Trollope reports enterprises are in "trough of disillusionment" with AI agents, as only the biggest companies successfully move from lab to production. Key challenge is aggregating unstructured data from multiple sources for agent decision-making. |
| 20260128-openai-prism | 2026-01-28 | OpenAI | OpenAI Launches Prism for Scientific Research | https://openai.com/index/introducing-prism | OpenAI introduced Prism, a new tool for scientific research and academic writing. The announcement has generated significant discussion about its impact on peer review systems and academic publishing workflows. |
| 20260128-ai2-sera | 2026-01-28 | AI2 | AI2 Releases SERA Open Coding Agents with 54.2% SWE-Bench Performance | https://allenai.org/blog/open-coding-agents | AI2 launched SERA (Soft-verified Efficient Repository Agents), achieving 54.2% on SWE-Bench Verified. The 32B model matches commercial performance at 57× lower cost than SWE-smith and includes Claude Code integration. Training costs only $400-$12,000 depending on target performance. |
| 20260127-moltbot-security | 2026-01-27 | Moltbot | Clawdbot Sheds Skin to Become Moltbot, Can't Slough Off Security Issues | https://www.theregister.com/2026/01/27/clawdbot_moltbot_security_concerns/ | The massively hyped agentic personal assistant Clawdbot rebrands as Moltbot but security experts question why anyone would install it, citing ongoing security vulnerabilities and privacy concerns with the AI agent platform. |
| 20260127-cursor-secure-indexing | 2026-01-27 | Cursor | Cursor Launches Secure Codebase Indexing for Large Repos | https://www.cursor.com/blog/secure-codebase-indexing | Cursor introduces secure codebase indexing that cuts time-to-first-query from hours to seconds on the largest repositories by securely reusing a teammate's existing index, enabling instant AI assistance on massive codebases. |
| 20260127-anthropic-funding-350b | 2026-01-27 | Anthropic | Anthropic Closes $10B+ Funding at $350B Valuation | https://www.cnbc.com/2026/01/27/anthropic-fundraising-microsoft-nvidia.html | Anthropic closed funding round above initial $10B target at $350B valuation, with potential for $15B if Microsoft and Nvidia participate. Coatue and Singapore's GIC led the round. CEO Dario Amodei reports company generated close to $10B revenue last year. |
| 20260127-salesforce-army-deal | 2026-01-27 | Salesforce | Salesforce Signs $5.6B Deal to Bring Agentic AI to US Army | https://www.theregister.com/2026/01/27/salesforce_5b_deal_agentic_ai_us_army/ | Salesforce secured a 10-year, $5.6 billion contract with the US Army to deploy Missionforce cloud analytics as foundation for future agentic AI across the service and wider DoD. Deal follows Army's existing AI adoption plans with Scale AI, Anduril, and Microsoft. |
| 20260127-ralph-wiggum-claude | 2026-01-27 | Anthropic | Developer Creates "Ralph Wiggum Loop" for Autonomous Claude Code Generation | https://www.theregister.com/2026/01/27/ralph_wiggum_claude_loops/ | Developer Geoff Huntley created a bash loop that feeds Claude's output back into itself until it produces working code. The technique can clone commercial software for ~$10/hour of compute. Anthropic has created an official Ralph Wiggum Plugin for Claude Code. |
| 20260127-kimi-k25 | 2026-01-27 | Kimi | Kimi Releases K2.5 Open-Source Visual SOTA-Agentic Model | https://www.kimi.com/blog/kimi-k2-5.html | Kimi released K2.5, a 1T parameter model (32B active) with MIT license, featuring agent swarm capabilities with up to 100 sub-agents and 1,500 tool calls. The model claims SOTA performance on vision tasks and includes native INT4 quantization. |
| 20260127-greptile-code-review | 2026-01-27 | Greptile | Greptile Declares "AI Code Review Bubble" as Competition Intensifies | https://www.greptile.com/blog/ai-code-review-bubble | Greptile analyzes the surge in AI code review tools from major players including OpenAI, Anthropic, Cursor, and Cognition. The company advocates for independent code validation agents separate from coding agents, predicting a future of fully automated code approval workflows. |
| 20260127-nvidia-groq-acquisition | 2026-01-27 | Nvidia | Nvidia Acquires Groq AI Chip Tech for $20 Billion | https://www.cnbc.com/2025/12/24/nvidia-buying-ai-chip-startup-groq-for-about-20-billion-biggest-deal.html | Nvidia announced its largest acquisition ever, purchasing AI chip startup Groq's assets for $20 billion. The deal brings Groq's language processing unit technology and talent to Nvidia, though Groq will continue operating independently under new CEO Simon Edwards. |
| 20260126-microsoft-maia-200 | 2026-01-26 | Microsoft | Microsoft Unveils Maia 200 AI Chip with Blackwell-Level Performance | https://www.theregister.com/2026/01/26/microsoft_maia_200/ | Microsoft announced Maia 200, a 144B transistor inference chip offering 10 petaFLOPS of FP4 performance at 750W. The chip is 30% cheaper than competing AI silicon and features 216GB HBM3e memory with 7TB/s bandwidth, optimized specifically for large model inference. |
| 20260126-dropbox-cursor | 2026-01-26 | Cursor | Dropbox Accepts 1M+ Lines of Agent-Generated Code Monthly with Cursor | https://www.cursor.com/blog/dropbox | Dropbox uses Cursor to index over 550,000 files and build an AI-native SDLC, accepting more than 1 million lines of agent-generated code monthly while improving PR velocity and cycle time across their engineering organization. |
| 20260126-chatgpt-containers | 2026-01-26 | OpenAI | ChatGPT Containers Now Support Bash, Node.js, and 10+ Languages | https://simonwillison.net/2026/Jan/26/chatgpt-containers/ | ChatGPT's container feature received a major undocumented upgrade, now supporting direct Bash commands, Node.js, and 10 additional programming languages. New capabilities include pip/npm package installation via proxy and a container.download tool for fetching web files. |
| 20260125-claude-swarms | 2026-01-25 | Anthropic | Claude Code's New Hidden Feature: Swarms | https://news.ycombinator.com/item?id=46743908 | Claude Code introduces a new "Swarms" feature enabling coordinated multi-agent coding capabilities, marking a significant advancement in AI-assisted development workflows. |
| 20260124-openai-codex | 2026-01-24 | OpenAI | OpenAI Publishes Research on Unrolling the Codex Agent Loop | https://openai.com/index/unrolling-the-codex-agent-loop/ | OpenAI released new research on improving Codex agent performance through loop unrolling techniques, demonstrating significant improvements in code generation accuracy and efficiency. |
| 20260121-cognition-devin-review | 2026-01-21 | Cognition | Devin Review: AI to Stop Code Slop | https://www.cognition.ai/blog/devin-review | Cognition launches Devin Review to address the new bottleneck in AI-assisted development: code review. As code generation becomes easier, the tool augments human attention with AI to quickly review and understand complex PRs. |
| 20260121-cursor-salesforce | 2026-01-21 | Cursor | Salesforce Ships Higher-Quality Code Across 20,000 Developers with Cursor | https://www.cursor.com/blog/salesforce | Over 90% of Salesforce's 20,000 developers now use Cursor, driving double-digit improvements in cycle time, PR velocity, and code quality across the organization's massive engineering teams. |